DROP INDEX CUSTOMER.CU_DID_WID_LAST_FIRST USING GSI
DROP INDEX CUSTOMER.CU_CID_DID_WID USING GSI
DROP INDEX DISTRICT.DI_ID_WID_NOID_TAX USING GSI
DROP INDEX NEW_ORDER.NO_DID_WID_OID USING GSI
DROP INDEX ORDERS.OR_DID_WID_ID_CID USING GSI
DROP INDEX ORDERS.OR_CID_DID_WID_ID_CAID_EID USING GSI
DROP INDEX ORDER_LINE.OL_OID_DID_WID_IID_AMOUNT USING GSI
DROP INDEX WAREHOUSE.WH_ID_TAX USING GSI
DROP INDEX STOCK.ST_IID_WID_QUANTITY USING GSI
DROP PRIMARY INDEX ON CUSTOMER USING GSI
DROP PRIMARY INDEX ON DISTRICT USING GSI
DROP PRIMARY INDEX ON HISTORY USING GSI
DROP PRIMARY INDEX ON ITEM USING GSI
DROP PRIMARY INDEX ON NEW_ORDER USING GSI
DROP PRIMARY INDEX ON ORDERS USING GSI
DROP PRIMARY INDEX ON ORDER_LINE USING GSI
DROP PRIMARY INDEX ON STOCK USING GSI
DROP PRIMARY INDEX ON WAREHOUSE USING GSI
CREATE INDEX CU_DID_WID_LAST_FIRST ON CUSTOMER(C_D_ID, C_W_ID, C_LAST, C_FIRST) USING GSI WITH {"defer_build": true, "num_replica":replicas}
CREATE INDEX CU_CID_DID_WID ON CUSTOMER(C_D_ID, C_ID, C_W_ID) USING GSI WITH {"defer_build": true, "num_replica":replicas}
CREATE INDEX DI_ID_WID_NOID_TAX ON DISTRICT(D_ID, D_W_ID, D_NEXT_O_ID, D_TAX) USING GSI WITH {"defer_build": true, "num_replica":replicas}
CREATE INDEX NO_DID_WID_OID ON NEW_ORDER(NO_D_ID, NO_W_ID, NO_O_ID) USING GSI WITH {"defer_build": true, "num_replica":replicas}
CREATE INDEX OR_DID_WID_ID_CID ON ORDERS(O_D_ID, O_W_ID, O_ID, O_C_ID) USING GSI WITH {"defer_build": true, "num_replica":replicas}
CREATE INDEX OR_CID_DID_WID_ID_CAID_EID ON ORDERS(O_C_ID, O_D_ID, O_W_ID, O_ID DESC, O_CARRIER_ID, O_ENTRY_D) USING GSI WITH {"defer_build": true, "num_replica":replicas}
CREATE INDEX OL_OID_DID_WID_IID_AMOUNT ON ORDER_LINE(OL_O_ID, OL_D_ID, OL_W_ID, OL_I_ID, OL_AMOUNT) USING GSI WITH {"defer_build": true, "num_replica":replicas}
CREATE INDEX WH_ID_TAX ON WAREHOUSE(W_ID, W_TAX) USING GSI WITH {"defer_build": true, "num_replica":replicas}
CREATE INDEX ST_IID_WID_QUANTITY ON STOCK(S_I_ID, S_W_ID, S_QUANTITY) USING GSI WITH {"defer_build": true, "num_replica":replicas}
SELECT keyspace_id, state FROM system:indexes
SELECT keyspace_id, state FROM system:indexes WHERE state != 'online'

